version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/wd2tb/docker-compose/torrents/config/sonarr:/config
      - /mnt/wd2tb/docker-compose/torrents/data/tv:/tv
      - /mnt/wd2tb/docker-compose/torrents/data/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/wd2tb/docker-compose/torrents/config/radarr:/config
      - /mnt/wd2tb/docker-compose/torrents/data/movies:/movies
      - /mnt/wd2tb/docker-compose/torrents/data/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/wd2tb/docker-compose/torrents/config/lidarr:/config
      - /mnt/wd2tb/docker-compose/torrents/data/music:/music
      - /mnt/wd2tb/docker-compose/torrents/data/downloads:/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/wd2tb/docker-compose/torrents/config/transmission:/config
      - /mnt/wd2tb/docker-compose/torrents/data/downloads:/downloads
      - /mnt/wd2tb/docker-compose/torrents/data/watch:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /mnt/wd2tb/docker-compose/torrents/config/jellyfin:/config
      - /mnt/wd2tb/docker-compose/torrents/data/tv:/data/tvshows
      - /mnt/wd2tb/docker-compose/torrents/data/movies:/data/movies
    ports:
      - "8096:8096" # http
      - "8920:8920" # https
    restart: unless-stopped
